### PR TITLE
clear-linux: Add information about kvm-host bundle.

### PR DESCRIPTION
**Pull request by mrkz**
This commit adds general information about the kvm-host
bundle content and how to enable/start some services
that may be required when this bundle is installed.

Signed-off-by: Simental Magana, Marcos <marcos.simental.magana@intel.com>

### CODE REVIEW

**Comment by mltullis** [comment]
Thanks Marcos. Please confirm that you want this new topic to show up with other similar ones at https://clearlinux.org/documentation/clear-linux/bundles/bundles.html. If so, I'll merge this and then add a reference to the bundles.rst index file so that this new topic will build in context with the others.

**Comment by mltullis** [comment]
Per Marcos, this pull request is on hold while the team sorts out what will be in the doc vs. shifting some bits to the OS.

**Comment by miguelinux** [comment]
lgtm

@rcaballeromx the technical information is accurate.

@mrkz do you agree to continue with this PR?

**Comment by mrkz** [comment]
Thank you @rcaballeromx

**Pull request merged**
